name: advance_text_field
description: an advance text field for flutter, customizable and contain two button for save and make editable text field.
version: 0.0.4
author: mohammad mohammady<mohammad.mohammady.73@gmail.com>
homepage: https://github.com/appiranian/advance_text_field.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

